#pragma once
#include "Command.h"
#include "ListCollabTasks.h"
#include "LogoutCommand.h"
#include "GetTaskCommand.h"
#include "LoginCommand.h"
#include "FinishCommand.h"
#include "ExitCommand.h"
#include "AsignTaskCommand.h"
#include "RegisterCommand.h"
#include "AddTaskCommand.h"
#include "ListTasksCommand.h"
#include "StartTaskCommand.h"
#include "UpdateTaskCommand.h"
#include "AddDashboardCommand.h"
#include "RemoveFromDashCommand.h"
#include "ListDateCommand.h"
#include "ListCompletedCommand.h"
#include "Command.h"
#include "DeleteTaskCommand.h"
#include "DeleteCollabCommand.h"
#include "CreateCollabCommand.h"
#include "ListCollabsCommand.h"
#include "AddInCollabCommand.h"
#include "System.h"

Command* createCommand(const String& command, System* s);
